spring:
  application:
    name: cloud-eureka-server7002
server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
    appname: eureka7002
  server:
    enable-self-preservation: false #关闭自我保护机制
  client:
    register-with-eureka: false #表示不要向注册中心注册自己
    fetch-registry: false #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/