server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign-order
eureka:
  client:
    register-with-eureka: true #将订单服务注册进Eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
logging:
  level:
    com.battle.springcloud.service.PaymentFeignService: debug
management:
  endpoints:
    web:
      exposure:
        include: beans